version: '3.8'

services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 Rest_api.flask_app:app
    ports:
      - "5000:5000"
    restart: always

  ui:
    build: .
    command: streamlit run streamlit_app/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:5000
    depends_on:
      - api
    restart: always
